FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Install system dependencies for PostgreSQL (if you're using PostgreSQL)
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && apt-get clean

# Copy the requirements.txt file into the container
COPY requirements.txt /app/

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

EXPOSE 8080

ENV DJANGO_SETTINGS_MODULE=todo_app.settings

RUN pip install gunicorn

CMD ["gunicorn", "--bind", "0.0.0.0:8080", "todo_app.wsgi:application"]
